spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        requests-in:
          destination: requests
          contentType: application/json
        requests-out:
          destination: requests
          contentType: application/json